# Simple Makefile for Go project

.PHONY: run build clean

# Run the application
run:
	@echo "Running the application..."
	go run planner-microservice

# Build the application
build:
	@echo "Building the application..."
	go build -o app main.go

# Clean build artifacts
clean:
	@echo "Cleaning build artifacts..."
	rm -f app
